// <auto-generated />
using System;
using M_invantori.Infarastucher.EFcor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M_invantori.Infarastucher.EFcor.Migrations
{
    [DbContext(typeof(invantoriContext))]
    partial class invantoriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domin_invantorii.InvantoriyAgg.Invantoriyy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationData")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<double>("UnitParice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("INvantoriyy");
                });

            modelBuilder.Entity("Domin_invantorii.InvantoriyAgg.Invantoriyy", b =>
                {
                    b.OwnsMany("Domin_invantorii.InvantoriyAgg.InvantoriyOpration", "Oprations", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Count")
                                .HasColumnType("bigint");

                            b1.Property<long>("CurrentCount")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<long>("InvantoriyId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("Opration")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("OprationDate")
                                .HasColumnType("datetime2");

                            b1.Property<long>("OprationId")
                                .HasColumnType("bigint");

                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.ToTable("Oprations");

                            b1.WithOwner("Invantoriy")
                                .HasForeignKey("Id");

                            b1.Navigation("Invantoriy");
                        });

                    b.Navigation("Oprations");
                });
#pragma warning restore 612, 618
        }
    }
}
